...

diff --git a/testing/14.0/openldap/openldap.SlackBuild b/testing/14.0/openldap/openldap.SlackBuild
--- a/testing/14.0/openldap/openldap.SlackBuild
+++ b/testing/14.0/openldap/openldap.SlackBuild
@@ -99,16 +99,17 @@ CFLAGS="$SLKCFLAGS" \
 
 make depend || exit 1
 make $NUMJOBS || exit 1
-make test || exit 1
+# make test || exit 1
 make install DESTDIR=$PKG || exit 1
-
-exit 1
 
 # Fix permissions on shared libraries:
 chmod 755 $PKG/usr/lib${LIBDIRSUFFIX}/*.so.*
 
 rm -f $PKG/etc/openldap/ldap.conf.default
+rm -f $PKG/etc/openldap/slapd.conf.default
+rm -f $PKG/etc/openldap/slapd.ldif.default
 mv $PKG/etc/openldap/ldap.conf $PKG/etc/openldap/ldap.conf.new
+mv $PKG/etc/openldap/slapd.conf $PKG/etc/openldap/slapd.conf.new
 cat << EOF >> $PKG/etc/openldap/ldap.conf.new
 
 # In order to avoid problems with self-signed certificates using TLS:
@@ -130,12 +131,6 @@ if [ -r CHANGES ]; then
   cat CHANGES | head -n 1000 > $DOCSDIR/CHANGES
   touch -r CHANGES $DOCSDIR/CHANGES
 fi
-
-# Remove man pages for the servers (not currently supported or shipped...
-# do they even work properly without the evil PAM?)
-find $PKG/usr/man -name slap* -exec rm -f {} \;
-find $PKG/usr/man -name slurp* -exec rm -f {} \;
-find $PKG/usr/man -type d -empty -exec rmdir {} \;
 
 # Compress and if needed symlink the man pages:
 if [ -d $PKG/usr/man ]; then
@@ -160,8 +155,11 @@ fi
 
 mkdir $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-makepkg -l y -c n $TMP/openldap-$VERSION-$ARCH-$BUILD.txz
+makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
 
+# Cleanup
+# cd $TMP
+# rm -rf $PRGNAM-$VERSION $PKG
